# -*- coding: utf-8 -*-
"""App de Análise de Indeferimentos SREVV

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKh_IGR00XgPe2xJ9Y7MzCL4ltWKzDqe
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# 1. Meu nome
# A identidade do criador do aplicativo.
NOME_AUTOR = "Thiago Pereira da Silva"

# 2. Tema do aplicativo
# O tema principal é a análise dos motivos de indeferimento do processo seletivo da SREVV.
TEMA_APLICATIVO = "Análise de Indeferimentos do PSS - Edital 40/2024 (SREVV)"

# Configurações iniciais da página
st.set_page_config(
    page_title=TEMA_APLICATIVO,
    page_icon="🔍",
    layout="wide"
)

# Título principal do aplicativo
st.title(f"🔍 {TEMA_APLICATIVO}")
st.markdown("---")

# 3. Divisão das seções do app
# Usamos a barra lateral (sidebar) para criar um menu de navegação entre as seções.
st.sidebar.header("Menu de Navegação")
secao_selecionada = st.sidebar.radio(
    "Escolha uma seção:",
    ("Início e Resumo", "Visualização de Dados", "Sobre o Projeto")
)

# Seção 1: Início e Resumo
if secao_selecionada == "Início e Resumo":
    st.header("Início e Resumo do Processo Seletivo")
    st.write("Bem-vindo ao aplicativo de análise dos indeferimentos do Processo Seletivo Simplificado (PSS) - Edital 40/2024 da Superintendência Regional de Educação de Vila Velha (SREVV).")
    st.write("Este aplicativo tem como objetivo apresentar e visualizar os principais motivos que levaram aos indeferimentos, ajudando a identificar padrões e possíveis pontos de melhoria no processo de inscrição.")

    st.subheader("Resumo (Dados Simulados)")
    st.markdown("""
    Esta seção é um resumo inicial que pode ser alimentado com dados em tempo real. Por exemplo:
    - **Total de Inscrições Processadas:** 5.320
    - **Total de Indeferimentos:** 1.250
    - **Taxa de Indeferimento:** 23.5%
    """)

# Seção 2: Visualização de Dados (placeholder para futura expansão)
elif secao_selecionada == "Visualização de Dados":
    st.header("Gráficos e Análise Detalhada")
    st.write("Esta seção é dedicada à apresentação de gráficos e tabelas que visualizam os dados de indeferimento. Os gráficos abaixo são baseados em dados simulados para demonstrar o potencial de análise.")

    # Simulação de dados de indeferimento
    dados_simulados_indeferimento = {
        'Motivo': ['Falta de Documento de Identidade', 'Formulário Preenchido Incorretamente', 'Comprovante de Endereço Inválido', 'Certificado de Conclusão Não Anexado'],
        'Contagem': [550, 320, 180, 200]
    }
    df_indeferimento = pd.DataFrame(dados_simulados_indeferimento)

    st.subheader("Distribuição dos Motivos de Indeferimento")

    # Exemplo de gráfico de pizza
    fig, ax = plt.subplots()
    ax.pie(df_indeferimento['Contagem'], labels=df_indeferimento['Motivo'], autopct='%1.1f%%', startangle=90)
    ax.axis('equal') # Garante que o gráfico de pizza seja circular
    st.pyplot(fig)

    st.subheader("Tabela de Dados")
    st.dataframe(df_indeferimento)

# Seção 3: Sobre o Projeto
elif secao_selecionada == "Sobre o Projeto":
    st.header("Sobre o Aplicativo e a Fonte de Dados")
    st.markdown(f"**Criador:** {NOME_AUTOR}")
    st.markdown("---")

    # 4. Bases de dados que imagina usar
    st.subheader("Fontes de Dados")
    st.markdown("""